mysql:
  host: 192.168.1.98
  port: 3306
  database: MineAuth_DB
  username: MineAuth_SQL
  password: MineAuth_8396

security:
  maxAttempts: 5
  blockMillis: 120000 # 2 минуты в миллисекундах
  kickDelaySeconds: 60 # через сколько секунд без авторизации кикать

# другие настройки...
telegram:
  mode: generate_on_bot
  bot_token: "YOUR_BOT_TOKEN_HERE"
  bot_username: "YOUR_BOT_NAME_HERE"
