mysql:
  host: localhost
  port: 3306
  database: Your_Auth_Database_Here
  username: Your_MySQL_User_Here
  password: Your_MySQL_Password_Here

security:
  maxAttempts: 5
  blockMillis: 120000 # 2 минуты в миллисекундах
  kickDelaySeconds: 60 # через сколько секунд без авторизации кикать

# другие настройки...
telegram:
  mode: generate_on_bot
  bot_token: "YOUR_BOT_TOKEN_HERE"
  bot_username: "YOUR_BOT_NAME_HERE"
